"""
Chargeback and forecasting ORM models.

Tables:
  - chargebacks — monthly cost records per tenant
  - forecasts   — future capacity and cost predictions
"""

from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin


class ChargebackStatus(str, enum.Enum):
    DRAFT = "draft"
    FINALISED = "finalised"
    INVOICED = "invoiced"
    DISPUTED = "disputed"


class ForecastMethod(str, enum.Enum):
    LINEAR = "linear"
    EXPONENTIAL = "exponential"
    MOVING_AVERAGE = "moving_average"


# ---------------------------------------------------------------------------
# Chargeback
# ---------------------------------------------------------------------------

class Chargeback(Base, TimestampMixin):
    """
    Monthly chargeback record for a single tenant.

    One row per tenant per billing month. Captures average and peak usage,
    computed costs in both primary and secondary currencies, and any manual
    adjustments (e.g. credits, discounts).
    """

    __tablename__ = "chargebacks"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id", "billing_year", "billing_month",
            name="uq_chargeback_tenant_period",
        ),
        Index("ix_chargebacks_tenant_id", "tenant_id"),
        Index("ix_chargebacks_period", "billing_year", "billing_month"),
        Index("ix_chargebacks_status", "status"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    tenant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tenants.id", ondelete="RESTRICT"), nullable=False
    )
    billing_year: Mapped[int] = mapped_column(Integer, nullable=False)
    billing_month: Mapped[int] = mapped_column(Integer, nullable=False)  # 1–12
    status: Mapped[ChargebackStatus] = mapped_column(
        Enum(ChargebackStatus, name="chargeback_status"),
        nullable=False,
        default=ChargebackStatus.DRAFT,
    )

    # Usage during the billing period
    avg_size_gb: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    peak_size_gb: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_objects: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    billable_gb: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0,
        doc="The GB value used for cost calculation (usually avg or peak)",
    )

    # Rates applied
    rate_gbp_per_gb: Mapped[float] = mapped_column(Float, nullable=False)
    rate_usd_per_gb: Mapped[float] = mapped_column(Float, nullable=False)
    exchange_rate_gbp_usd: Mapped[float] = mapped_column(Float, nullable=False)

    # Computed costs (before adjustments)
    subtotal_gbp: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    subtotal_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # VAT
    vat_rate: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    vat_amount_gbp: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    vat_amount_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Adjustments (credits / discounts; negative = reduction)
    adjustment_gbp: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    adjustment_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    adjustment_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Final totals
    total_gbp: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Metadata
    finalised_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finalised_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    invoice_reference: Mapped[str | None] = mapped_column(String(256), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    tenant: Mapped["Tenant"] = relationship("Tenant", back_populates="chargebacks")  # type: ignore[name-defined]


# ---------------------------------------------------------------------------
# Forecast
# ---------------------------------------------------------------------------

class Forecast(Base, TimestampMixin):
    """
    Capacity and cost forecast for a cluster or tenant.

    Generated by the forecasting service based on historical usage trends.
    Multiple rows may exist for the same target and date (different methods).
    """

    __tablename__ = "forecasts"
    __table_args__ = (
        Index("ix_forecasts_cluster_id", "cluster_id"),
        Index("ix_forecasts_tenant_id", "tenant_id"),
        Index("ix_forecasts_forecast_date", "forecast_date"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    cluster_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("clusters.id", ondelete="CASCADE"), nullable=True
    )
    tenant_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=True
    )
    forecast_date: Mapped[datetime] = mapped_column(
        Date, nullable=False, doc="The future date this forecast is for"
    )
    method: Mapped[ForecastMethod] = mapped_column(
        Enum(ForecastMethod, name="forecast_method"),
        nullable=False,
        default=ForecastMethod.LINEAR,
    )
    forecasted_size_gb: Mapped[float] = mapped_column(Float, nullable=False)
    forecasted_cost_gbp: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    forecasted_cost_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    confidence_lower_gb: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Lower bound of confidence interval"
    )
    confidence_upper_gb: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Upper bound of confidence interval"
    )
    r_squared: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="R² value of the regression model (0.0–1.0)"
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# Resolve forward reference
from app.models.storage import Tenant  # noqa: E402, F401
