"""
Reporting ORM model.

Table:
  - reports — metadata for generated reports (email, Excel, PDF)
"""

from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin


class ReportType(str, enum.Enum):
    DAILY_EMAIL = "daily_email"
    SIX_HOUR_EMAIL = "six_hour_email"
    MONTHLY_EXCEL = "monthly_excel"
    MONTHLY_PDF = "monthly_pdf"
    CHARGEBACK = "chargeback"
    CAPACITY_FORECAST = "capacity_forecast"
    AD_HOC = "ad_hoc"


class ReportStatus(str, enum.Enum):
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"
    EMAILED = "emailed"


class Report(Base, TimestampMixin):
    """
    Tracks every report generated by the platform.

    Stores metadata (type, period, status, file path) and the list of
    recipients. Actual report files are stored on disk; this table provides
    the audit trail and enables re-send functionality.
    """

    __tablename__ = "reports"
    __table_args__ = (
        Index("ix_reports_cluster_id", "cluster_id"),
        Index("ix_reports_type_period", "report_type", "period_start"),
        Index("ix_reports_status", "status"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    cluster_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("clusters.id", ondelete="SET NULL"),
        nullable=True,
        doc="NULL = platform-wide report",
    )
    report_type: Mapped[ReportType] = mapped_column(
        Enum(ReportType, name="report_type"), nullable=False
    )
    status: Mapped[ReportStatus] = mapped_column(
        Enum(ReportStatus, name="report_status"),
        nullable=False,
        default=ReportStatus.PENDING,
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    period_start: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    period_end: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    file_path: Mapped[str | None] = mapped_column(
        String(1024), nullable=True, doc="Absolute path to the generated report file on disk"
    )
    file_size_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    recipients: Mapped[str | None] = mapped_column(
        Text, nullable=True, doc="Comma-separated email addresses"
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_by: Mapped[str] = mapped_column(
        String(128), nullable=False, default="system",
        doc="Username or 'system' for automated reports"
    )
    generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    emailed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
